version: "3"

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"

  product-app:
    container_name: product_app
    build:
      context: Backend
      dockerfile: multistage.Dockerfile
    environment:
      DB_URL: ${DB_URL_INTERNAL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PRODUCT_APP_PORT: ${PRODUCT_APP_PORT}
      PAGINATION_SIZE: ${PAGINATION_SIZE}
    ports:
      - ${PRODUCT_APP_PORT}:${PRODUCT_APP_PORT}
    depends_on:
      db:
        condition: service_started
        restart: true
